# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f9a5e86a6097c6c3797d32bd9d0cbd743eaacf8838505d75e4c38a7998767c25c32112924e0183d72adacfeed4695820a7c0cd560da2caa9584363c2d604072

test:
  secret_key_base: 753ba8e6d962d9902bcbb508592fcae5a7ebf6809c28fc5291e2edd618e777f07593d98b6dbef80422fd27a6533bbaceba07d54fb000a6753a51b6f8d5f2b112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
